# Generated by Django 6.0 on 2025-12-24 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='required_skills',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
