# Generated by Django 6.0 on 2025-12-24 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_company_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_role',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='package',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
