# Generated by Django 6.0 on 2025-12-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_company_job_role_company_location_company_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='package',
            field=models.CharField(max_length=20),
        ),
    ]
