# Generated by Django 6.0 on 2026-01-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_remove_student_roll_no_student_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('PHY', 'Physics'), ('MATH', 'Mathematics'), ('CHEM', 'Chemistry'), ('BCOM', 'B.Com')], max_length=10)),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='interview_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.student')),
            ],
        ),
    ]
