# Generated by Django 6.0 on 2026-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_interviewquestion_student_interview_passed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interview_passed',
            new_name='is_interview_passed',
        ),
    ]
