# Generated by Django 6.0 on 2026-01-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_rename_interview_passed_student_is_interview_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='correct_option',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option4',
            field=models.CharField(default='', max_length=200),
        ),
    ]
