# Generated by Django 6.0 on 2026-01-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0009_remove_interviewquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='correct_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')]),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='option1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='option2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='option3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='option4',
            field=models.CharField(max_length=200),
        ),
    ]
