# Generated by Django 6.0 on 2026-01-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0010_alter_interviewquestion_correct_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='package',
        ),
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.CharField(default='COMPUTER SCIENCE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='min_cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='department',
            field=models.CharField(choices=[('CS', 'B.Sc Computer Science'), ('MATH', 'B.Sc Mathematics'), ('PHY', 'B.Sc Physics'), ('CHEM', 'B.Sc Chemistry'), ('STAT', 'B.Sc Statistics')], max_length=10),
        ),
    ]
