# Generated by Django 6.0 on 2026-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0011_remove_company_job_role_remove_company_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='department',
            field=models.CharField(choices=[('COMPUTER SCIENCE', 'B.Sc Computer Science'), ('PHYSICS', 'B.Sc Physics'), ('CHEMISTRY', 'B.Sc Chemistry'), ('MATHEMATICS', 'B.Sc Mathematics'), ('STATISTICS', 'B.Sc Statistics')], max_length=50),
        ),
    ]
