# Generated by Django 6.0 on 2026-01-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0013_company_created_at_student_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='company',
            name='department',
            field=models.CharField(choices=[('BSC COMPUTER SCIENCE', 'B.Sc Computer Science'), ('BSC MATHEMATICS', 'B.Sc Mathematics'), ('BSC PHYSICS', 'B.Sc Physics'), ('BSC CHEMISTRY', 'B.Sc Chemistry'), ('BSC STATISTICS', 'B.Sc Statistics')], max_length=50),
        ),
    ]
