# Generated by Django 6.0 on 2026-01-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0014_remove_company_created_at_alter_company_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_role',
            field=models.CharField(default='not specified', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='Not specified', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='package',
            field=models.CharField(default='Software Engineer', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='min_cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
