# Generated by Django 6.0 on 2026-01-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0015_company_job_role_company_location_company_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='correct_option',
            field=models.IntegerField(),
        ),
    ]
