# Generated by Django 6.0 on 2026-01-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0016_alter_interviewquestion_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='department',
            field=models.CharField(choices=[('CS', 'B.Sc Computer Science'), ('MATH', 'B.Sc Mathematics'), ('PHY', 'B.Sc Physics'), ('CHEM', 'B.Sc Chemistry'), ('STAT', 'B.Sc Statistics')], max_length=10),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='correct_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')]),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'B.Sc Computer Science'), ('MATH', 'B.Sc Mathematics'), ('PHY', 'B.Sc Physics'), ('CHEM', 'B.Sc Chemistry'), ('STAT', 'B.Sc Statistics')], max_length=10),
        ),
    ]
