# Generated by Django 6.0 on 2026-01-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0017_alter_company_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewresult',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='department',
            field=models.CharField(choices=[('CS', 'B.Sc Computer Science'), ('MATH', 'B.Sc Mathematics'), ('PHY', 'B.Sc Physics'), ('CHEM', 'B.Sc Chemistry'), ('STAT', 'B.Sc Statistics')], default='Bsc computer science', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='placement.student'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewresult',
            unique_together={('student', 'department')},
        ),
    ]
