# Generated by Django 6.0 on 2026-01-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0018_rename_date_interviewresult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='company',
            name='min_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
